### ISSUE TITLE
Default task end date to the day-after-today

### ISSUE THREAD

**Issue by octacian** [mkermani144/wanna#224]
When I create a task using Wanna, I very often find myself setting the end date to the day-after-today. Would it be possible to make this a default, just as the start date defaults to today's date?

**Comment by mkermani144** [comment]
Thank you for your feature request. 🙏

I think this is a case special to you. For instance, it's rare for me to add a task whose start date is today and its end date is tomorrow.
However, some of the dates (such as today and tomorrow) are special, and we'll probably add a feature in the next versions so that the user can set start/end date to these special ones without the need to exactly specify the day number in the date picker.
So feel free to add another issue to request such a feature, but I think this issue should be closed.

**Comment by mkermani144** [comment]
It's also possible to give the user the ability to set default start/end dates in the settings as he/she favors.
