### ISSUE TITLE
Application cannot resize vertically

### ISSUE THREAD

**Issue by Hadesy2k** [mkermani144/wanna#245]
The application is not vertically resizable, therefore the bottom is covered by the desktop task bar. My desktop environment is Deepin.

![Screenshot](https://i.imgur.com/7ZviCVw.png)

**Comment by mkermani144** [comment]
@Hadesy2k 
Thanks for your bug report. This bug is reported in #229, and will be fixed in the next version of Wanna. Just take a look at a [workaround](https://github.com/mkermani144/wanna/issues/229#issuecomment-343716255) in the mentioned issue if this size limit sucks.
So I will close this issue.
